### ISSUE TITLE
Unable to run octovue

### ISSUE THREAD

**Issue by EnnajimiYassine** [shodushi/octovue#1]
Hi @shodushi ,

First of all thanks for your great work. I tried to install octovue (on my mac) but it doesn't seem to work. I'm stuck at this page
![image](https://user-images.githubusercontent.com/16754780/71751491-0997ff00-2e7c-11ea-82f8-1424866e0c4b.png)
when I type the Ip and the API key of my octoprint 3d printer nothing happens. 
Please find the logs of my console
[192.168.0.25-1578088148310.log](https://github.com/shodushi/octovue/files/4021052/192.168.0.25-1578088148310.log)

Thanks for your help !

**Comment by shodushi** [comment]
Hi @EnnajimiYassine ,

I fixed the initial config screen. Should work now, tested the initial steps on my mac. Seems like I broke something somewhere at some time... :-)

**Comment by EnnajimiYassine** [comment]
Hi @shodushi ,
Thanks a lot for your help. I confirm that now I can connect to octovue, but I still see the printer offline ( I can see all the 3d files in my octoprint , control the motors, temperature but I cannot see the current temp / ongoing print ) 

![image](https://user-images.githubusercontent.com/16754780/71781195-25121f80-2fcc-11ea-8960-bcb30650d5f6.png)
![image](https://user-images.githubusercontent.com/16754780/71781203-38bd8600-2fcc-11ea-96fa-ed6ae7c1720e.png)

Edit : I face this issue only with google chrome, it's working perfectly with safari

**Comment by shodushi** [comment]
Ok, thats a bit strange, cause I mainly use chrome, I just updated to the latest version of chrome and can not reproduce it, maybe you are running an outdated version of chrome? Just a shot in the dark....

**Comment by EnnajimiYassine** [comment]
Hi @shodushi ,

I have the latest version of chrome Version 79.0.3945.88 (Official Build) (64-bit).
Everything is working fine with safari, is there a way to switch printer on/off with Gcode instead of IP ? Is it possible to add a custom command in the dashboard ? 

Thanks a lot !

**Comment by lbibass** [comment]
Hey there! I wanted to let you know that I am having the same problem as well, unfortunately. I can't see a way to save my config. It's just the same screen as @EnnajimiYassine posted.

**Comment by shodushi** [comment]
Hi @lbibass ,

did you check out the latest commit? ($> git pull && npm run build)

I fixed this 4 days ago.
After you enter your IP and API key a button "check connection" will appear and you can enter your printer settings and save the config.

**Comment by shodushi** [comment]
> Hi @shodushi ,
> 
> I have the latest version of chrome Version 79.0.3945.88 (Official Build) (64-bit).
> Everything is working fine with safari, is there a way to switch printer on/off with Gcode instead of IP ? Is it possible to add a custom command in the dashboard ?
> 
> Thanks a lot !

Hi @EnnajimiYassine,

yes I can implement buttons with custom gcode commands in dashboard. As far as I read you can wire pins to your ATX PSU or board of your printer to turn it on (M80) and off (M81), if your printer supports this. Unfortunately I can not test this with my printer cause my Prusa i3 does not support this. I will notify you, when I implemented the custom buttons...

br

**Comment by shodushi** [comment]
Hi @EnnajimiYassine,

I just implemented custom gcode command buttons in dashboard.
Just add a new gcode-button widget, specify a button text/label and the gcode command that should be executed on button-click.
Terminal tab then shows the command being executed.

Have fun

br

**Comment by lbibass** [comment]
> Hi @lbibass ,
> 
> did you check out the latest commit? ($> git pull && npm run build)
> 
> I fixed this 4 days ago.
> After you enter your IP and API key a button "check connection" will appear and you can enter your printer settings and save the config.

Okay, I installed it onto another printer and that part worked correctly. However, there is another problem. It doesn't seem to want to connect to my printer, while stock octoprint works just fine.

**Comment by EnnajimiYassine** [comment]
@lbibass : Have you tried with another brower ? 
@shodushi : I tested the Gcode Button and it's working like a charm 👍 ! Regarding the Psu I use the M80 and M81  commands (PSU control plugin with octoprint that switch a gpio pin when receiving M80/M81). I can test it for you :)
I also have some suggestions  : 
1) Be able to lock the dashboard to prevent accidental delete of widgets 
2) Be able to add a widget for pausing / canceling the print like in the print page 
3) Be able to group the Gcode buttons 
4) Be able to add  a widget with the list of the local gcode files ? 
I want to be able to do everything from the dashboard screen 

Thanks a lot !

**Comment by shodushi** [comment]
@lbibass I rewrote the connectionhandling, maybe you can check if it's working better now..

@EnnajimiYassine I like your suggestions. I already implemented the dashboard un/locking. I will have a look at the rest when I find some time...
